export const ORDER_STATUS = {
  CRIADO: "CRIADO",
  AGUARDANDO_PAGAMENTO: "AGUARDANDO_PAGAMENTO",
  PAGO: "PAGO",
  ENVIADO_PARA_FORNECEDOR: "ENVIADO_PARA_FORNECEDOR",
  ACEITO_PELO_FORNECEDOR: "ACEITO_PELO_FORNECEDOR",
  EM_SEPARACAO: "EM_SEPARACAO",
  EM_TRANSITO: "EM_TRANSITO",
  ENTREGUE: "ENTREGUE",
  CANCELADO: "CANCELADO",
  FALHA_FORNECEDOR: "FALHA_FORNECEDOR"
};