// backend/orders/orders.status.js

export const ORDER_STATUS = {
  // início
  CRIADO: "CRIADO",
  AGUARDANDO_PAGAMENTO: "AGUARDANDO_PAGAMENTO",
  PAGO: "PAGO",

  // fornecedor
  ENVIADO_PARA_FORNECEDOR: "ENVIADO_PARA_FORNECEDOR",
  ACEITO_PELO_FORNECEDOR: "ACEITO_PELO_FORNECEDOR",
  EM_SEPARACAO: "EM_SEPARACAO",
  EM_TRANSITO: "EM_TRANSITO",

  // final
  ENTREGUE: "ENTREGUE",
  CANCELADO: "CANCELADO",
  FALHA_FORNECEDOR: "FALHA_FORNECEDOR"
};